### ISSUE TITLE
Don't check ignored files

### ISSUE THREAD

**Issue by borekb** [TomasHubelbauer/vscode-markdown-link-suggestions#10]
@TomasHubelbauer

The paths on the following screenshot are gitignored in our repo but still checked by this extension:

![image](https://user-images.githubusercontent.com/101152/44659758-89e75e00-aa05-11e8-8249-299a98de1543.png)

Is that possibly related to some deeper VSCode issue, like https://github.com/Microsoft/vscode/issues/50874?

**Comment by TomasHubelbauer** [comment]
Thank you, I will check this and see if I can improve detecting ignored files a bit more, VS Code API seems to be a little spotty when it comes to this indeed, but I believe I will be able to come up with a working solution nontheless. I think I will be able to fix this this upcoming weekend.

**Comment by TomasHubelbauer** [comment]
Once again, thank you for reporting this. I have decided to prioritize internal rewrite which should help enable some new features I have in mind and make future work easier over fixing this at this time in an interest of best allocating the time I can give this extension. I hope it's not a problem to wait for this a bit longer, if it significantly breaks your workflow, I'll revert that decision and focus on a hotfix for this in the current codebase.

**Comment by borekb** [comment]
It's not critical for my workflow and am happy to wait for a newer and even more awesome version :)

**Comment by TomasHubelbauer** [comment]
This should be fixed in `12.0.3` using the workaround described in my latest comment in microsoft/vscode#48674.

I am worried that code might be a little bit unstable, I wish VS Code had better SCM API which could be used to query file status.

I will keep monitoring Application Insights for failures coming from that logic, but it defaults to providing files from potentially ignored directories, so from the user PoV it should always do something reasonable. 

Worst case it could just keep finding diagnostics issues in your ignored file, but hopefully it doesn't anymore. I will leave this open for a bit in case this release won't go as smoothly as I am hoping it will.
