### ISSUE TITLE
Correct link reported as not existing

### ISSUE THREAD

**Issue by maziac** [TomasHubelbauer/vscode-markdown-link-suggestions#22]
@TomasHubelbauer

Many thanks for this great vscode extension.

I only have a small problem:
I have following link:
~~~
![](documentation/images/z80_sample_prg_run.gif)
~~~
which exists but MD Link Suggestions reports:
~~~
The path /documentation/images/z80_sample_prg_run.gif doesn't exist on the disk.
~~~
it seems like it's creating an absolute path from it.

I found that in the 13.0.0 version on a mac.

The md file I used can be found here:
https://github.com/maziac/z80-sample-program/blob/master/readme.md

**Comment by TomasHubelbauer** [comment]
Hi, sorry, this is a known issue, but I am not maintaining the extension at the moment, so I can't fix it. I want to take a look at these issues soon, so when I have some time to dedicate to the maintenance of this extension, I will do so, but at the moment, I cannot make any promises as to when that will be.

**Comment by tom1700** [comment]
I know it's a little bit old, but maybe it will help someone.

I've experienced a similar problem. So I've downloaded the project to debug it. And it works 🤯 

When I build the extension locally and load it using 
```
code --install-extension vscode-markdown-link-suggestions-13.0.0.vsix
```
it works, but when I use the marketplace version it doesn't.

**Comment by TomasHubelbauer** [comment]
Yeah I haven't published in a while, sorry, I'm pretty bad about maintaining my extensions. I'll publish tomorrow so this gets cleared.

**Comment by RoBaaaT** [comment]
@TomasHubelbauer Thanks for the great extension and sorry for reviving this old issue.

I had the same issue as well and was also able to fix it by building the current version locally and manually installing it, like @tom1700 did.
It would be great if you could update the marketplace version.
 
Note that I also had to update the vscode dependency to the latest version (1.1.37) to be able to build, because the update server used for the package changed (microsoft/vscode#119822).

**Comment by TomasHubelbauer** [comment]
No need to apologize! I appreciate you using the extension. I'll make no promises about the date but I'll try to update the extension whenever I have some time and energy to work on my own source. Hope you have a good one 😌

**Comment by Creat1veM1nd** [comment]
Having the same issue and would like to try building it locally as @tom1700  and @RoBaaaT did. 
Since I am not familiar with building extension I would like to ask if you could point me to a How-To for that ?

Thanks in advance!

**Comment by RoBaaaT** [comment]
@Creat1veM1nd This may help: https://code.visualstudio.com/api/working-with-extensions/publishing-extension. You basically have to clone the repository, run `npm install` to install dependencies, then install `vsce` and run `vsce generate` in your local copy of the repository. This will give you the .vsix file that you can install in VSCode instead of the version from the marketplace.

Note: In my case I also had to bump the `vscode` dependency version in `package.json` to 1.1.37 as the old version of the module points to a binary on some Microsoft server that does not exist anymore (see https://github.com/microsoft/vscode/issues/119822). If you don't do that you will probably get an error when running `npm install`.

**Comment by Creat1veM1nd** [comment]
Thanks! 

I gave it a quick try but got a bunch of errors. When trying to install node.js newest version, I did not work at all. So, I will give it a try later again.

**Comment by Creat1veM1nd** [comment]
Sadly I never got that working, probably doing something wrong on my end. But since it seems this plugin is not longer maintained, I will just go with uninstalling it.

**Comment by TomasHubelbauer** [comment]
Hi folks! Sorry for not maintaining the extension, I have not been very active on any of my personal projects for a long time now for personal reasons. That being said, VS Code seems to have rolled out a feature called "MarkDown link Intellisense" in a recent release and it should make this extension obsolete! Please check it out and let me know how you feel about it :) https://code.visualstudio.com/updates/v1_64#_markdown-path-intellisense I will likely pull this extension completely if this native feature covers its functionality.

**Comment by Creat1veM1nd** [comment]
Just tested it (didn't had the latest version of VSCode yet). It seems to work like your plugin did, so I guess this native feature covers it.

**Comment by TomasHubelbauer** [comment]
Sounds great. I am going to go ahead and close this issue. Eventually I will archive this repository unless I can think of a meaningful subset of functionality this extension could provide that the native experience might not. On a quick glance, it seems like exclude support is not there yet for example. But overall I am extremely happy with this being native now and if it continues to get maintenance attention as a part of VS Code, it will likely not be necessary to keep this extension going at all.
