### ISSUE TITLE
Option to disable suggestions inside [] and suggestions from headers

### ISSUE THREAD

**Issue by insanetesterftw** [TomasHubelbauer/vscode-markdown-link-suggestions#3]
@TomasHubelbauer

Suggestions inside [] are not very useful. Rarely one wants "something.md" as link text and it's too easy to press enter at the suggestion and then have to correct it. Besides that unhelpful suggestion is distracting.

An option to disable suggestions to link to headers is also necessary in the event that, just like me, a person has too many files and too many similar files with similar headers. In this case the suggestions just become noise.

Options to disable both are appreciated. Thank you kindly.

**Comment by TomasHubelbauer** [comment]
Great feedback, I use this almost exclusively for a repo which all it does is interlink files, but I sort of snuck this specific feature to what should be a more global extension to be useful to more people.

I will start with adding the settings you suggest and in time will split into two extensions, one for just link suggestions (what most people want) and one with a bundle of other features for interlinking local MarkDown files (what few people will need).

**Comment by TomasHubelbauer** [comment]
I just released a version 7.0.0 which introduces a configuration setting for disabling suggestions within `[]` and defaults to not provide those, as I've come to the conclusion it is a niche feature which probably only my workflow benefits from. After you update your extensions, you should without any extra action immediately see the desired behavior.

Disabling suggestions of header links is going to come next, because I forgot to also do that for this release. I will probably default that setting to still provide those suggestions, though, because I feel like it brings a lot of benefit (especially because there is a diagnostic for making sure the header links stay valid) and with the configuration setting it will be simple to turn off for people who have a lot of files with a lot of headers where it makes the suggestions too noisy.

**Comment by TomasHubelbauer** [comment]
Closing this as it should work the way you want to now, @insanetesterftw. Let's reopen if issues surface.
