### ISSUE TITLE
Suggestions not appearing

### ISSUE THREAD

**Issue by borekb** [TomasHubelbauer/vscode-markdown-link-suggestions#4]
@TomasHubelbauer

I've tried on a couple of repos, including [our public one](https://github.com/versionpress/versionpress) but also several smaller, and I never get suggestions as in the GIF in README.

I've tried in an empty VSCode with only this extension enabled. Not sure what I could be doing wrong.

VSCode 1.25.1 and 1.26.0-insider
Extension version: 7.0.3 (and also reproducible with previous versions)

**Comment by borekb** [comment]
Yes, sure. I should have noted that I invoke suggestions manually via Ctrl+Space if that matters.

**Comment by TomasHubelbauer** [comment]
I see. This uncovered a bug I will fix, I didn't account for that trigger kind. You end up seeing the default VS Code list of suggestions which only give you keywords picked out from the repository context, right? Like this:

![image](https://user-images.githubusercontent.com/6831144/43101525-e5ceb112-8ec8-11e8-90df-0f8a97a2adc7.png)

**Comment by borekb** [comment]
Exactly.

**Comment by TomasHubelbauer** [comment]
In that case I will cut a proper release soon instead, I know where the issue lies now.

**Comment by TomasHubelbauer** [comment]
I have cut a new release, `7.0.4`, you should see it up soon. Ctrl + Space (or any remapped shortcut for the suggestion triggering command) will not work as expected.

Please be aware that this still only triggers after `(` (and `[` if enabled). I will need to do more work to allow it to work at arbitrary places (both within `(` and `)` and at any place in the document, where it would recognize no link syntax has been typed yet and would build it up).

It's doable, but will require me to correctly parse out existing paths at the suggestion point (if any) and make the suggestions relative to that path, which is not a use case I have needed yet, so I haven't implemented it for myself.

If you would benefit from that being supported, I will be more than happy to implement it.

Please let me know if 7.0.4 fixed your issue.

**Comment by borekb** [comment]
I don't see the new version yet, has it been published already?

**Comment by TomasHubelbauer** [comment]
Mea culpa, please retry.

**Comment by borekb** [comment]
I have to admit that our repo is a bit bigger but still, this is the first time I've seen VSCode crash as it was trying to load the path suggestions 😄 

![image](https://user-images.githubusercontent.com/101152/43103323-f84bbf2e-8ecd-11e8-8479-e3dc4c08284a.png)

**Comment by borekb** [comment]
On a smaller repo, it works nicely!

**Comment by TomasHubelbauer** [comment]
LOL! I'm sorry about that, I do have a very old to-do caching the repo file and header index, looks like it is high time to resolve it. Unfortunately VS Code doesn't support loading in the suggestions asynchronously because of unresolved UX questions around that behavior, so first-time suggestions experience still needs to be taken into account, but I am confident I will find a nice compromise there (say not waiting for the header index and just show file index, which is much faster to generate).

**Comment by borekb** [comment]
Does it suggest every file in the workspace? Sort of like quick pick?

**Comment by borekb** [comment]
That sounds great.

For suggesting all files in the workspace, isn't it possible to somehow tap into the quick pick UI and let VSCode do the hard work? Probably not, right?

**Comment by TomasHubelbauer** [comment]
I will make sure to consult the API again now that we have new releases to see if there is a way to get the information I need (or at least portions of it) from VS Code proper, that would make my extension much simpler.

However I don't think there is a way, because the extension API is more high-level than that.

I do need a solution for repository/workspace level caching anyway for my other extensions, so I will make that into a shared component, but I don't think there is a way fully around it.

**Comment by TomasHubelbauer** [comment]
I will close this in favor of a new, better focused, issue #7 I just created to track specifically the performance issue. The problem with the trigger character I believe was resolved. Please feel free to report any further annoyances and I will do my best to fix them speedily.
