### ISSUE TITLE
GitHub-compatible anchors

### ISSUE THREAD

**Issue by borekb** [TomasHubelbauer/vscode-markdown-link-suggestions#5]
@TomasHubelbauer

`## Environments vs. projects` will be rendered as `file.md#environments-vs-projects` by GitHub but this extension is not happy about it:

![image](https://user-images.githubusercontent.com/101152/43079411-59318bfc-8e8d-11e8-86b4-a43b8b05896d.png)

This is probably relatively hard to get right as different Markdown renderers will produce different results but for example Markdown All in One added [`markdown.extension.toc.githubCompatibility` option](https://github.com/neilsustc/vscode-markdown#supported-settings), maybe there could be something similar for Markdown Link Suggestions (or even using that existing option if it exists).

**Comment by TomasHubelbauer** [comment]
There are multiple concerns here:

- Making sure link target with anchors explicitly typed out to make the GitHub preview clicking work are not reported as broken
- Making sure previously generated link anchors by this very extension (when choosing an option with a header link) will remain working, otherwise I'd be introducing a BC
- Making sure VS Code Ctlr+click remains functional

Since VS Code Ctrl+click is not bothered by whether the link anchor has a period it in or not, I could safely switch to the GitHub way. However, that train has passed, because of point 2, it would be very uncool to break existing users by declaring some of their links my extension itself generated by not valid anymore.

You are right that I don't want to venture down the rabbit hole of making this logic work with every possible MarkDown renderer. It seems to me like one option here would be to support both, because VS Code does, too, in Ctrl+click. That way old generated link anchors will remain valid and new ones will be changed to generate GitHub compatible code. I will see what GitLab, BitBucket and Gitea do and if it makes sense, introduce a setting for it, but I do think I could get by with just changing the behavior to removing the periods.

I will report back with my findinds.

**Comment by TomasHubelbauer** [comment]
I was able to verify both GitHub and GitLab strip the periods in the generated URL fragment. BitBucket won't allow me to reset my password and Gitea is straight up broken, so as a punishment I will ignore the behavior of both services: 💪

I have changed  the extension so that it generates fragments without periods, but added an exception which will keep fragments with periods working as to not break previously generated ones.

I've cut a new version, 9.0.0, which I believe addresses this, please verify and let me know!

**Comment by borekb** [comment]
Cool, I can confirm this works as expected.
