### ISSUE TITLE
Custom protocols signals error in Problems panel

### ISSUE THREAD

**Issue by dbobak** [TomasHubelbauer/vscode-markdown-link-suggestions#6]
@TomasHubelbauer

When writing in markdown, I'm using custom protocol handler to link to the Zotero item (zotero://).

The extension misinterprets it and signals error as the file does not exist on disk, see attache image. Maybe would it be possible to add an option to list custom protocols?

![image](https://user-images.githubusercontent.com/6285546/43143674-978c76cc-8f5b-11e8-860c-f8bea0d0ec8e.png)

**Comment by TomasHubelbauer** [comment]
I have cut a new release, 8.0.0. Please update to it and see if you can confirm my fix resolved your issue.

I am not sure why I went with a blacklist of protocol, instead of a whitelist, when I initially did. But I changed the code to diagnose URLs only if they lack a protocol (which is indicative of relative file paths) or explicitly say the protocol is `file`.

**Comment by dbobak** [comment]
It's fixed now, thank you!
