### ISSUE TITLE
Suggest file headings after typing `#`

### ISSUE THREAD

**Issue by borekb** [TomasHubelbauer/vscode-markdown-link-suggestions#8]
@TomasHubelbauer

Due to performance issues on larger repositories (#4, #7), I cannot currently use file suggestions in their full form. However, I think it should be feasible to scope it to current file only, for example, when I type this (`|` is a cursor):

```
[link to a section of a file](#|)
```

and press Ctrl+Space, I would get a list of anchors from the current file. Would make my life a little bit easier :)

**Comment by TomasHubelbauer** [comment]
I've cut a new release, 10.0.0, which adds a mode that kicks in after `)[#` and suggest only current file headers.

For `$REASONS` this was not possible to do completely nicely. Not a problem, I plan on revamping the suggestion logic to support artitrary suggesting triggering points within the MarkDown link instead of just the first character of either the text or the URL, so I bolted a solution on in the meantime which will serve your need and when I get to refactoring, I'll make sure to preserve it.

Please let me know if all is well, I'm closing for now and will reopen in case of problems.

**Comment by borekb** [comment]
It works beautifully, thank you!

**Comment by TomasHubelbauer** [comment]
While the initial suggestion list is populated, typing to narrow it down doesn't work as per #11. This problem will be fixed soon and will remain tracked in the related issue #11.

**Comment by TomasHubelbauer** [comment]
This has been fixed together with #11.
